const path = require('path');
const glob = require('glob');
const fs = require('fs');

let OUTPUT_PATH = path.join(__dirname, '../src/routes.js');
let ROUTE_TEMPLATE = `{
  name: '{{name}}',
  path: '{{route_path}}',
  component: () => import('{{path}}'),
}`;
let MAIN_TEMPLATE = `/* Automatically generated by './scripts/build-routes.js' */
import Home from './home';

export default [
{
  path: '/',
  name: 'home',
  component: Home,
},{{list}}
];`;

const files = glob.sync('src/components/**.vue');
const routeTemplates = [];

files.forEach(item => {
  const name = item.split('/').pop().split('.')[0];
  routeTemplates.push(ROUTE_TEMPLATE
    .replace('{{name}}', name)
    .replace('{{route_path}}', `/${name.toLowerCase()}`)
    .replace('{{path}}', item.replace('src/', './')));
});

fs.writeFile(OUTPUT_PATH, MAIN_TEMPLATE.replace('{{list}}', routeTemplates), {}, () => {
  console.log('-----auto generated components.json success-----');
});
